/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package fr.uga.pddl4j.parser.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 13;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 14;
  /** RegularExpression Id. */
  int DEFINE = 15;
  /** RegularExpression Id. */
  int DOMAIN = 16;
  /** RegularExpression Id. */
  int PLAN = 17;
  /** RegularExpression Id. */
  int S_PLAN = 18;
  /** RegularExpression Id. */
  int BODY = 19;
  /** RegularExpression Id. */
  int REQUIREMENTS = 20;
  /** RegularExpression Id. */
  int TYPES = 21;
  /** RegularExpression Id. */
  int EITHER = 22;
  /** RegularExpression Id. */
  int CONSTANTS = 23;
  /** RegularExpression Id. */
  int PREDICATES = 24;
  /** RegularExpression Id. */
  int AXIOM = 25;
  /** RegularExpression Id. */
  int AXIOM_VAR = 26;
  /** RegularExpression Id. */
  int AXIOM_CONTEXT = 27;
  /** RegularExpression Id. */
  int AXIOM_IMPLIES = 28;
  /** RegularExpression Id. */
  int FUNCTIONS = 29;
  /** RegularExpression Id. */
  int ACTION = 30;
  /** RegularExpression Id. */
  int PARAMETERS = 31;
  /** RegularExpression Id. */
  int PRECONDITION = 32;
  /** RegularExpression Id. */
  int EFFECT = 33;
  /** RegularExpression Id. */
  int PREFERENCE = 34;
  /** RegularExpression Id. */
  int WHEN = 35;
  /** RegularExpression Id. */
  int DURATIVE_ACTION = 36;
  /** RegularExpression Id. */
  int DURATION = 37;
  /** RegularExpression Id. */
  int CONDITION = 38;
  /** RegularExpression Id. */
  int DERIVED = 39;
  /** RegularExpression Id. */
  int PROBLEM = 40;
  /** RegularExpression Id. */
  int P_DOMAIN = 41;
  /** RegularExpression Id. */
  int P_PROBLEM = 42;
  /** RegularExpression Id. */
  int PLANVARS = 43;
  /** RegularExpression Id. */
  int OBJECTS = 44;
  /** RegularExpression Id. */
  int INIT = 45;
  /** RegularExpression Id. */
  int GOAL = 46;
  /** RegularExpression Id. */
  int METRIC = 47;
  /** RegularExpression Id. */
  int DESIRED_OUTCOME = 48;
  /** RegularExpression Id. */
  int OPTIONAL = 49;
  /** RegularExpression Id. */
  int MAIN = 50;
  /** RegularExpression Id. */
  int STRIPS = 51;
  /** RegularExpression Id. */
  int TYPING = 52;
  /** RegularExpression Id. */
  int NEGATIVE_PRECONDITIONS = 53;
  /** RegularExpression Id. */
  int DISJUNCTIVE_PRECONDITIONS = 54;
  /** RegularExpression Id. */
  int EQUALITY = 55;
  /** RegularExpression Id. */
  int EXISTENTIAL_PRECONDITIONS = 56;
  /** RegularExpression Id. */
  int UNIVERSAL_PRECONDITIONS = 57;
  /** RegularExpression Id. */
  int QUANTIFIED_PRECONDITIONS = 58;
  /** RegularExpression Id. */
  int CONDITIONAL_EFFECTS = 59;
  /** RegularExpression Id. */
  int ACTION_COSTS = 60;
  /** RegularExpression Id. */
  int FLUENTS = 61;
  /** RegularExpression Id. */
  int NUMERIC_FLUENTS = 62;
  /** RegularExpression Id. */
  int OBJECT_FLUENTS = 63;
  /** RegularExpression Id. */
  int GOAL_UTILITIES = 64;
  /** RegularExpression Id. */
  int ADL = 65;
  /** RegularExpression Id. */
  int DURATIVE_ACTIONS = 66;
  /** RegularExpression Id. */
  int DERIVED_PREDICATES = 67;
  /** RegularExpression Id. */
  int TIMED_INITIAL_LITERALS = 68;
  /** RegularExpression Id. */
  int PREFERENCES = 69;
  /** RegularExpression Id. */
  int CONSTRAINTS = 70;
  /** RegularExpression Id. */
  int CONTINUS_EFFECTS = 71;
  /** RegularExpression Id. */
  int DOMAIN_AXIOMS = 72;
  /** RegularExpression Id. */
  int DURATION_INEQUALITIES = 73;
  /** RegularExpression Id. */
  int IS_PERCEIVABLE = 74;
  /** RegularExpression Id. */
  int ALLOW_EXPLORE = 75;
  /** RegularExpression Id. */
  int GREATER = 76;
  /** RegularExpression Id. */
  int LESS = 77;
  /** RegularExpression Id. */
  int GEQUAL = 78;
  /** RegularExpression Id. */
  int LEQUAL = 79;
  /** RegularExpression Id. */
  int EQUAL = 80;
  /** RegularExpression Id. */
  int MUL = 81;
  /** RegularExpression Id. */
  int DIV = 82;
  /** RegularExpression Id. */
  int ADD = 83;
  /** RegularExpression Id. */
  int SUB = 84;
  /** RegularExpression Id. */
  int ASSIGN = 85;
  /** RegularExpression Id. */
  int SCALE_UP = 86;
  /** RegularExpression Id. */
  int SCALE_DOWN = 87;
  /** RegularExpression Id. */
  int INCREASE = 88;
  /** RegularExpression Id. */
  int DECREASE = 89;
  /** RegularExpression Id. */
  int OR = 90;
  /** RegularExpression Id. */
  int AND = 91;
  /** RegularExpression Id. */
  int IMPLY = 92;
  /** RegularExpression Id. */
  int NOT = 93;
  /** RegularExpression Id. */
  int FORALL = 94;
  /** RegularExpression Id. */
  int EXISTS = 95;
  /** RegularExpression Id. */
  int IMPLIES_TO = 96;
  /** RegularExpression Id. */
  int ONEOF = 97;
  /** RegularExpression Id. */
  int SEQUENCE = 98;
  /** RegularExpression Id. */
  int SE_ACTION = 99;
  /** RegularExpression Id. */
  int IF = 100;
  /** RegularExpression Id. */
  int SUBPLAN = 101;
  /** RegularExpression Id. */
  int WHILE = 102;
  /** RegularExpression Id. */
  int ALWAYS = 103;
  /** RegularExpression Id. */
  int SOMETIME = 104;
  /** RegularExpression Id. */
  int WITHIN = 105;
  /** RegularExpression Id. */
  int AT_MOST_ONCE = 106;
  /** RegularExpression Id. */
  int SOMETIME_AFTER = 107;
  /** RegularExpression Id. */
  int SOMETIME_BEFORE = 108;
  /** RegularExpression Id. */
  int ALWAYS_WITHIN = 109;
  /** RegularExpression Id. */
  int HOLD_DURING = 110;
  /** RegularExpression Id. */
  int HOLD_AFTER = 111;
  /** RegularExpression Id. */
  int AT = 112;
  /** RegularExpression Id. */
  int START = 113;
  /** RegularExpression Id. */
  int END = 114;
  /** RegularExpression Id. */
  int OVER = 115;
  /** RegularExpression Id. */
  int ALL = 116;
  /** RegularExpression Id. */
  int TOTAL_TIME = 117;
  /** RegularExpression Id. */
  int TOTAL_COST = 118;
  /** RegularExpression Id. */
  int MAXIMIZE = 119;
  /** RegularExpression Id. */
  int MINIMIZE = 120;
  /** RegularExpression Id. */
  int IS_VIOLATED = 121;
  /** RegularExpression Id. */
  int VAR_DURATION = 122;
  /** RegularExpression Id. */
  int CONTINUOUS_VARIABLE = 123;
  /** RegularExpression Id. */
  int NUMBER_TYPE = 124;
  /** RegularExpression Id. */
  int OBJECT_TYPE = 125;
  /** RegularExpression Id. */
  int BOOLEAN = 126;
  /** RegularExpression Id. */
  int VARIABLE_SYMBOL = 127;
  /** RegularExpression Id. */
  int SYMBOL = 128;
  /** RegularExpression Id. */
  int NUMBER = 129;
  /** RegularExpression Id. */
  int DIGIT = 130;
  /** RegularExpression Id. */
  int LETTER = 131;
  /** RegularExpression Id. */
  int SEPARATOR = 132;
  /** RegularExpression Id. */
  int PRINTABLE = 133;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\";\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"(\"",
    "\")\"",
    "\"define\"",
    "\"domain\"",
    "\"plan\"",
    "\":plan\"",
    "\":body\"",
    "\":requirements\"",
    "\":types\"",
    "\"either\"",
    "\":constants\"",
    "\":predicates\"",
    "\":axiom\"",
    "\":vars\"",
    "\":context\"",
    "\":implies\"",
    "\":functions\"",
    "\":action\"",
    "\":parameters\"",
    "\":precondition\"",
    "\":effect\"",
    "\"preference\"",
    "\"when\"",
    "\":durative-action\"",
    "\":duration\"",
    "\":condition\"",
    "\":derived\"",
    "\"problem\"",
    "\":domain\"",
    "\":problem\"",
    "\":planvars\"",
    "\":objects\"",
    "\":init\"",
    "\":goal\"",
    "\":metric\"",
    "<DESIRED_OUTCOME>",
    "\":optional\"",
    "\":main\"",
    "\":strips\"",
    "\":typing\"",
    "\":negative-preconditions\"",
    "\":disjunctive-preconditions\"",
    "\":equality\"",
    "\":existential-preconditions\"",
    "\":universal-preconditions\"",
    "\":quantified-preconditions\"",
    "\":conditional-effects\"",
    "\":action-costs\"",
    "\":fluents\"",
    "\":numeric-fluents\"",
    "\":object-fluents\"",
    "\":goal-utilities\"",
    "\":adl\"",
    "\":durative-actions\"",
    "\":derived-predicates\"",
    "\":timed-initial-literals\"",
    "\":preferences\"",
    "\":constraints\"",
    "\":continus-effects\"",
    "\":domain-axioms\"",
    "\":duration-inequalities\"",
    "\":isperceivable\"",
    "\":allow_explore\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"assign\"",
    "\"scale-up\"",
    "\"scale-down\"",
    "\"increase\"",
    "\"decrease\"",
    "\"or\"",
    "\"and\"",
    "\"imply\"",
    "\"not\"",
    "\"forall\"",
    "\"exists\"",
    "\"-->\"",
    "\"oneof\"",
    "\"sequence\"",
    "\"action\"",
    "\"if\"",
    "\"subplan\"",
    "\"while\"",
    "\"always\"",
    "\"sometime\"",
    "\"within\"",
    "\"at-most-once\"",
    "\"sometime-after\"",
    "\"sometime-before\"",
    "\"always-within\"",
    "\"hold-during\"",
    "\"hold-after\"",
    "\"at\"",
    "\"start\"",
    "\"end\"",
    "\"over\"",
    "\"all\"",
    "\"total-time\"",
    "\"total-cost\"",
    "\"maximize\"",
    "\"minimize\"",
    "\"is-violated\"",
    "\"?duration\"",
    "\"#t\"",
    "\"number\"",
    "\"object\"",
    "<BOOLEAN>",
    "<VARIABLE_SYMBOL>",
    "<SYMBOL>",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "<SEPARATOR>",
    "<PRINTABLE>",
  };

}
