package com.surgical.decision3.common.constant;

public class SceneConstants
{
	public static String SCENE_INTRAOPERATIVE_EVENT_INITIALIZE = "INTRAOPERATIVE_INITIALIZE";
	public static String SCENE_INTRAOPERATIVE_NAME = "INTRAOPERATIVE_SCENE"; //INTRAOPERATIVE_SCENE
	
	//Login Page
	public static String SCENE_PREOPERATIVE_NAME_LOGIN = "PREOPERATIVE_SCENE_LOGIN";
	public static String SCENE_PREOPERATIVE_EVENT_LOGIN_PROCESS = "PREOPERATIVE_SCENE_EVENT_PROCESS_LOGIN";		//Process Login
	
	
	//Registration Page
	public static String SCENE_PREOPERATIVE_NAME_REGISTRATION = "PREOPERATIVE_SCENE_REGISTRATION";
	public static String SCENE_PREOPERATIVE_EVENT_REGISTRATION_PROCESS = "PREOPERATIVE_SCENE_EVENT_PROCESS_REGISTRATION";		//Receive Registration Data
	
	//Domain Selection Page
	public static String SCENE_PREOPERATIVE_NAME_DOMAIN_SELECTION = "PREOPERATIVE_SCENE_DOMAIN_SELECTION";
	public static String SCENE_PREOPERATIVE_EVENT_DOMAIN_INITIAL  = "PREOPERATIVE_SCENE_EVENT_DOMAIN_SELECTION_INITIAL";				//Load available domains, subdomains, and procedures
	public static String SCENE_PREOPERATIVE_EVENT_DOMAIN_SELECTED = "PREOPERATIVE_SCENE_EVENT_DOMAIN_SELECTION_SELECTED";				//Send selected case
	public static String SCENE_PREOPERATIVE_EVENT_DOMAIN_RESUME_LATEST_PATIENT_CASE = "PREOPERATIVE_SCENE_EVENT_DOMAIN_SELECTION_RESUME_LATEST_PATIENT_CASE";				//Send selected case
	
	//Case Selection Page
	public static String SCENE_PREOPERATIVE_NAME_CASE_SELECTION           = "PREOPERATIVE_SCENE_CASE_SELECTION";			
	public static String SCENE_PREOPERATIVE_EVENT_CASE_SELECTION_INITIAL  = "PREOPERATIVE_SCENE_EVENT_CASE_SELECTION_INITIAL";		//Load available case of all sub procedure by selected procedure
	public static String SCENE_PREOPERATIVE_EVENT_CASE_SELECTION_SELECTED = "PREOPERATIVE_SCENE_EVENT_CASE_SELECTION_SELECTED";		//Send selected case
	
	//Patient History Page
//	public static String SCENE_PREOPERATIVE_NAME_PATIENT_HISTORY = "PREOPERATIVE_CASE_SELECTION_SCENE";			
//	public static String SCENE_PREOPERATIVE_EVENT_PATIENT_HISTORY_INITIAL  = "PREOPERATIVE_CASE_SELECTION_SCENE_INITIAL";		//Load patient history
//
//	//Radio Graph Selection Page
//	public static String SCENE_PREOPERATIVE_NAME_RADIOGRAPH = "PREOPERATIVE_RADIOGRAPH_SCENE";
//	public static String SCENE_PREOPERATIVE_EVENT_RADIOGRAPH_INITIAL = "PREOPERATIVE_RADIOGRAPH_SCENE_INITIAL";	//Load list of radiograph by patient.
	
	//PLan
	public static String SCENE_PREOPERATIVE_NAME_PLAN = "PREOPERATIVE_SCENE_PLAN"; 
	public static String SCENE_PREOPERATIVE_EVENT_PLAN_INITIAL = "PREOPERATIVE_SCENE_EVENT_PLAN_INITIAL";
	public static String SCENE_PREOPERATIVE_EVENT_PLAN_SUBMIT = "PREOPERATIVE_SCENE_EVENT_PLAN_SUBMIT";
	
	//Tool Selection Page
	public static String SCENE_PREOPERATIVE_NAME_TOOL_SELECTION = "PREOPERATIVE_SCENE_TOOL_SELECTION";
	public static String SCENE_PREOPERATIVE_EVENT_TOOL_SELECTION_INITIAL = "PREOPERATIVE_TOOL_SELECTION_SCENE_INITIAL";	//Load tools from database.
	public static String SCENE_PREOPERATIVE_EVENT_TOOL_SELECTION_SELECTED = "PREOPERATIVE_TOOL_SELECTION_SCENE_SELECTED";	//Send selected inventory
}
